CREATE TABLE IF NOT EXISTS department
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    description character varying(1000),
    name character varying(255),
    sequence_number integer,
    CONSTRAINT department_pkey PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS public.persons
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    blood_type character varying(255),
    email character varying(255) NOT NULL,
    first_name character varying(255) NOT NULL,
    gender character varying(255),
    last_name character varying(255) NOT NULL,
    phone_number character varying(255) NOT NULL,
    city character varying(255),
    country character varying(255),
    state character varying(255),
    street character varying(255),
    zip_code character varying(255),
    joining_date timestamp(6) without time zone,
    serial_number integer,
    department_id bigint NOT NULL,
    role character varying(255),
    CONSTRAINT persons_pkey PRIMARY KEY (id),
    CONSTRAINT "FK1413d4hgxnvjt28gegyp3rq4" FOREIGN KEY (department_id)
        REFERENCES public.department (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT persons_blood_type_check CHECK (blood_type::text = ANY (ARRAY['A_POSITIVE'::character varying, 'A_NEGATIVE'::character varying, 'B_POSITIVE'::character varying, 'B_NEGATIVE'::character varying, 'AB_POSITIVE'::character varying, 'AB_NEGATIVE'::character varying, 'O_POSITIVE'::character varying, 'O_NEGATIVE'::character varying]::text[])),
    CONSTRAINT persons_gender_check CHECK (gender::text = ANY (ARRAY['MALE'::character varying, 'FEMALE'::character varying]::text[])),
    CONSTRAINT persons_role_check CHECK (role::text = ANY (ARRAY['PRINCIPAL'::character varying, 'PROFESSOR'::character varying, 'ASSISTANT_PROFESSOR'::character varying, 'UNDERGRADUATE_STUDENT'::character varying, 'GRADUATE_STUDENT'::character varying, 'LECTURER'::character varying, 'RESEARCHER'::character varying, 'TEACHING_ASSISTANT'::character varying]::text[]))
);

-- departments
INSERT INTO department(id, name, description, sequence_number)	VALUES
(1, 'Engineering Faculty', 'Faculty of All Engineering Mahors', 101 ),
(2, 'Business and Law Faculty', 'Faculty of Business and Law', 254 ),
(3, 'Science and Health Faculty', 'Faculty of Science and Health', 368 ),
(4, 'Creative and Cultural Industries Faculty', 'Faculty of Creative and Cultural Industries', 427 );


-- persons
INSERT INTO public.persons(id, first_name,last_name, email, phone_number, gender, blood_type, role, serial_number, joining_date, department_id, city, country, state, street, zip_code) VALUES
(1, 'Itadori', 'Yuji', 'itadori.yuji@gmail.com', '90 555 444 11 78', 'MALE', 'A_NEGATIVE', 'UNDERGRADUATE_STUDENT',11021, '2024-12-28 18:15:35.370000', 1, 'Tokyo', 'Japan', 'a state', 'a street', '00450' ),
(2, 'Naruto', 'Uzumaki', 'uzumaki.naruto@gmail.com', '90 848 147 11 78', 'MALE', 'O_NEGATIVE', 'UNDERGRADUATE_STUDENT',10091, '2024-12-18 18:15:35.370000', 2, 'Tokyo', 'Konoha', 'leaf village', 'leaf village', '00650' ),
(3, 'Kakashi', 'Hatake', 'kakashi.hatake@gmail.com', '90 148 447 61 78', 'MALE', 'AB_POSITIVE', 'ASSISTANT_PROFESSOR',16425, '2020-01-12 18:15:35.370000', 2, 'Tokyo', 'Konoha', 'leaf village', 'leaf village', '00650' ),
(4, 'Sasuke', 'Uchiha', 'sasuke.uchiha@gmail.com', '90 248 747 11 18', 'MALE', 'O_NEGATIVE', 'UNDERGRADUATE_STUDENT',10092, '2024-12-17 18:15:35.370000', 4, 'Tokyo', 'Konoha', 'orochimaru hideout', 'orochimaru cave', '00780' ),
(5, 'Orochimaru', 'Sennin', 'orochimaru.sennin@gmail.com', '90 218 577 11 18', 'MALE', 'O_POSITIVE', 'PRINCIPAL',787, '2010-12-01 18:15:35.370000', 4, 'Tokyo', 'Konoha', 'orochimaru hideout', 'orochimaru cave', '00780' ),
(6, 'Satoru', 'Gojo', 'satoru.gojo@gmail.com', '90 455 144 74 98', 'MALE', 'AB_NEGATIVE', 'ASSISTANT_PROFESSOR',268, '2016-05-28 18:15:35.370000', 1, 'Tokyo', 'Japan', 'a state', 'a street', '00450' ),
(7, 'Megumi', 'Fushiguro', 'megumi.fushiguro@gmail.com', '90 855 544 44 98', 'MALE', 'B_NEGATIVE', 'UNDERGRADUATE_STUDENT',9847, '2024-05-28 18:15:35.370000', 1, 'Tokyo', 'Japan', 'a state', 'a street', '00450' ),
(8, 'Kyojuro', 'Rengoku', 'kyojuro.rengoku@gmail.com', '90 787 644 31 78', 'MALE', 'A_POSITIVE', 'TEACHING_ASSISTANT',6554, '2022-12-28 18:15:35.370000', 3, 'Tokyo', 'Japan', 'Hashira Corps', 'hashira hideout', '00850' ),
(9, 'Tanjiro', 'Kamado', 'tanjiro.kamado@gmail.com', '90 475 684 31 78', 'MALE', 'B_POSITIVE', 'UNDERGRADUATE_STUDENT',6554, '2024-04-14 18:15:35.370000', 3, 'Tokyo', 'Japan', 'Hashira Corps', 'hashira hideout', '00850' ),
(10, 'Zenitsu', 'Agatsuma', 'zenitsu.agatsuma@gmail.com', '90 476 684 31 78', 'MALE', 'AB_POSITIVE', 'UNDERGRADUATE_STUDENT',6554, '2024-06-14 18:15:35.370000', 3, 'Tokyo', 'Japan', 'Hashira Corps', 'hashira hideout', '00850' ),
(11, 'Inosuke', 'Hashibira', 'inosuke.hashibira@gmail.com', '90 478 684 31 79', 'MALE', 'O_POSITIVE', 'UNDERGRADUATE_STUDENT', 6755, '2024-06-14 18:15:35.370000', 3, 'Tokyo', 'Japan', 'Hashira Corps', 'hashira hideout', '00850'),
(12, 'Shoto', 'Todoroki', 'shoto.todoroki@gmail.com', '90 123 456 78 90', 'MALE', 'AB_NEGATIVE', 'UNDERGRADUATE_STUDENT', 7841, '2024-02-20 10:30:00.000000', 2, 'Kyoto', 'Japan', 'Endeavor Agency', 'training center', '00560'),
(13, 'Izuku', 'Midoriya', 'izuku.midoriya@gmail.com', '90 321 654 78 90', 'MALE', 'A_POSITIVE', 'UNDERGRADUATE_STUDENT', 7412, '2024-01-15 09:45:00.000000',2, 'Kyoto', 'Japan', 'UA Academy', 'class dorms', '00700'),
(14, 'Eraser', 'Head', 'eraser.head@gmail.com', '90 456 987 32 10', 'MALE', 'O_NEGATIVE', 'ASSISTANT_PROFESSOR', 3652, '2018-07-10 14:20:00.000000', 2, 'Kyoto', 'Japan', 'UA Academy', 'teacher quarters', '00720'),
(15, 'Mikasa', 'Ackerman', 'mikasa.ackerman@gmail.com', '90 654 789 12 34', 'FEMALE', 'B_NEGATIVE', 'GRADUATE_STUDENT', 5298, '2023-09-22 16:10:00.000000', 4, 'Shiganshina', 'Eldia', 'Survey Corps', 'scout regiment base', '00900'),
(16, 'Levi', 'Ackerman', 'levi.ackerman@gmail.com', '90 147 258 36 98', 'MALE', 'AB_POSITIVE', 'PROFESSOR', 1125, '2015-03-11 11:05:00.000000', 4, 'Shiganshina', 'Eldia', 'Survey Corps', 'scout regiment HQ', '00910'),
(17, 'Eren', 'Yeager', 'eren.yeager@gmail.com', '90 369 258 14 78', 'MALE', 'O_POSITIVE', 'UNDERGRADUATE_STUDENT', 9632, '2024-08-05 08:30:00.000000', 4, 'Shiganshina', 'Eldia', 'Survey Corps', 'barracks', '00920'),
(18, 'Giyu', 'Tomioka', 'giyu.tomioka@gmail.com', '90 753 159 82 46', 'MALE', 'A_NEGATIVE', 'ASSISTANT_PROFESSOR', 2583, '2019-05-17 17:45:00.000000', 3, 'Tokyo', 'Japan', 'Hashira Corps', 'hashira headquarters', '00860'),
(19, 'Shinobu', 'Kocho', 'shinobu.kocho@gmail.com', '90 852 369 41 75', 'FEMALE', 'B_POSITIVE', 'ASSISTANT_PROFESSOR', 3486, '2020-08-19 12:00:00.000000', 3, 'Tokyo', 'Japan', 'Hashira Corps', 'butterfly estate', '00870'),
(20, 'Nezuko', 'Kamado', 'nezuko.kamado@gmail.com', '90 963 741 25 89', 'FEMALE', 'AB_POSITIVE', 'UNDERGRADUATE_STUDENT', 5697, '2024-09-30 14:10:00.000000', 3, 'Tokyo', 'Japan', 'Hashira Corps', 'hashira dorms', '00880'),
(21, 'All', 'Might', 'all.might@gmail.com', '90 111 222 33 44', 'MALE', 'O_POSITIVE', 'PRINCIPAL', 1, '2005-04-10 09:00:00.000000', 3, 'Kyoto', 'Japan', 'UA Academy', 'hero society', '01000'),
(22, 'Endeavor', 'Todoroki', 'endeavor.todoroki@gmail.com', '90 222 333 44 55', 'MALE', 'A_NEGATIVE', 'PROFESSOR', 2, '2010-06-15 10:30:00.000000', 2, 'Kyoto', 'Japan', 'UA Academy', 'hero agency', '01010'),
(23, 'Dabi', 'Todoroki', 'dabi.todoroki@gmail.com', '90 333 444 55 66', 'MALE', 'AB_NEGATIVE', 'GRADUATE_STUDENT', 3005, '2022-11-20 11:45:00.000000', 4, 'Kyoto', 'Japan', 'League of Villains', 'abandoned factory', '01020'),
(24, 'Hawks', 'Takami', 'hawks.takami@gmail.com', '90 444 555 66 77', 'MALE', 'B_POSITIVE', 'ASSISTANT_PROFESSOR', 4512, '2018-05-25 12:30:00.000000', 4, 'Kyoto', 'Japan', 'Hero Public Safety Commission', 'HQ', '01030'),
(25, 'Roronoa', 'Zoro', 'roronoa.zoro@gmail.com', '90 555 666 77 88', 'MALE', 'O_NEGATIVE', 'UNDERGRADUATE_STUDENT', 6012, '2024-03-10 13:20:00.000000', 1, 'East Blue', 'Grand Line', 'Straw Hat Pirates', 'Going Merry', '01100'),
(26, 'Monkey D.', 'Luffy', 'luffy.monkeyd@gmail.com', '90 666 777 88 99', 'MALE', 'A_POSITIVE', 'TEACHING_ASSISTANT', 7001, '2024-02-28 14:45:00.000000', 1, 'East Blue', 'Grand Line', 'Straw Hat Pirates', 'Thousand Sunny', '01110'),
(27, 'Sanji', 'Vinsmoke', 'sanji.vinsmoke@gmail.com', '90 777 888 99 00', 'MALE', 'B_POSITIVE', 'TEACHING_ASSISTANT', 8042, '2024-01-15 15:10:00.000000', 4, 'North Blue', 'Grand Line', 'Straw Hat Pirates', 'Baratie', '01120'),
(28, 'Robin', 'Nico', 'robin.nico@gmail.com', '90 888 999 00 11', 'FEMALE', 'AB_POSITIVE', 'LECTURER', 9210, '2019-06-22 16:00:00.000000', 3, 'Ohara', 'Grand Line', 'Revolutionary Army', 'archaeology center', '01130'),
(29, 'Shanks', 'Red-Haired', 'shanks.redhaired@gmail.com', '90 999 000 11 22', 'MALE', 'O_POSITIVE', 'PROFESSOR', 10002, '2015-12-10 17:25:00.000000', 3, 'West Blue', 'Grand Line', 'Red-Haired Pirates', 'Windmill Village', '01140'),
(30, 'Boa', 'Hancock', 'boa.hancock@gmail.com', '90 000 111 22 33', 'FEMALE', 'A_NEGATIVE', 'GRADUATE_STUDENT', 11012, '2023-07-18 18:10:00.000000', 4, 'Amazon Lily', 'Calm Belt', 'Kuja Pirates', 'empress palace', '01150'),
(31, 'Ichigo', 'Kurosaki', 'ichigo.kurosaki@bleach.com', '90 101 111 12 34', 'MALE', 'O_POSITIVE', 'UNDERGRADUATE_STUDENT', 5601, '2024-01-10 17:30:00.000000', 1, 'Karakura Town', 'Japan', 'Karakura', 'Karakura Shrine', '02340'),
(32, 'Rukia', 'Kuchiki', 'rukia.kuchiki@bleach.com', '90 202 222 23 45', 'FEMALE', 'A_NEGATIVE', 'ASSISTANT_PROFESSOR', 6743, '2020-07-14 14:20:00.000000', 2, 'Karakura Town', 'Japan', 'Karakura', 'Karakura Shrine', '02350'),
(33, 'Renji', 'Abarai', 'renji.abarai@bleach.com', '90 303 333 34 56', 'MALE', 'B_POSITIVE', 'LECTURER', 2345, '2022-06-10 16:00:00.000000', 3, 'Karakura Town', 'Japan', 'Karakura', 'Seireitei', '02360'),
(34, 'Orihime', 'Inoue', 'orihime.inoue@bleach.com', '90 404 444 45 67', 'FEMALE', 'AB_POSITIVE', 'TEACHING_ASSISTANT', 4532, '2024-02-18 10:25:00.000000', 1, 'Karakura Town', 'Japan', 'Karakura', 'Karakura Shrine', '02370'),
(35, 'Uryu', 'Ishida', 'uryu.ishida@bleach.com', '90 505 555 56 78', 'MALE', 'O_NEGATIVE', 'GRADUATE_STUDENT', 2347, '2024-03-22 18:35:00.000000', 2, 'Karakura Town', 'Japan', 'Karakura', 'Quincy Temple', '02380'),
(36, 'Byakuya', 'Kuchiki', 'byakuya.kuchiki@bleach.com', '90 606 666 67 89', 'MALE', 'AB_NEGATIVE', 'PRINCIPAL', 1234, '2018-05-05 13:15:00.000000', 4, 'Karakura Town', 'Japan', 'Seireitei', 'Kuchiki Manor', '02390'),
(37, 'Toshiro', 'Hitsugaya', 'toshiro.hitsugaya@bleach.com', '90 707 777 78 90', 'MALE', 'A_POSITIVE', 'ASSISTANT_PROFESSOR', 8765, '2019-12-12 11:50:00.000000', 2, 'Karakura Town', 'Japan', 'Seireitei', '10th Division', '02400'),
(38, 'Soi Fon', 'Fon', 'soi.fon@bleach.com', '90 808 888 89 01', 'FEMALE', 'O_POSITIVE', 'RESEARCHER', 6124, '2020-09-15 12:45:00.000000', 3, 'Karakura Town', 'Japan', 'Seireitei', '2nd Division', '02410'),
(39, 'Shunsui', 'Kyoraku', 'shunsui.kyoraku@bleach.com', '90 909 999 90 12', 'MALE', 'AB_NEGATIVE', 'LECTURER', 7103, '2018-11-30 15:20:00.000000', 3, 'Karakura Town', 'Japan', 'Seireitei', '8th Division', '02420'),
(40, 'Jushiro', 'Ukitake', 'jushiro.ukitake@bleach.com', '90 101 111 13 34', 'MALE', 'B_POSITIVE', 'PROFESSOR', 2932, '2017-08-14 09:30:00.000000', 4, 'Karakura Town', 'Japan', 'Seireitei', '13th Division', '02430');